// Two sensors on a Margay, discovered: the bus names them and the logger holds
// what answered (NW-Tests). Hand-written rather than generated by
// make_sketches.py, because it pairs with Programmed_Margay: on the same bus the
// two write the same table, byte for byte (LIBRARY-DESIGN.md section 16).
//
// The candidate table carries no names of its own. Every Schema 1 device names
// itself in Page 0, and each library's name() returns that same name as a
// compile-time literal, so an array of NW_Sensor* is the whole table. The order
// here is deliberately not address order: discovery walks the bus, so the
// columns come out in address order whatever order the candidates are declared
// in.
//
// The whole of setup() is one call. begin(candidates, n) brings the board up
// and then asks the bus, in that order, because the sensor rail and the bus
// switch are the board's and a bus asked before begin() answers nothing.
#include <Margay.h>
#include <Apis.h>
#include <Walrus_I2C.h>

Margay Logger(MODEL_3v0);  // update to match your hardware version
Apis distance;
Walrus stage;

NW_Sensor* candidates[] = {&stage, &distance};

uint32_t updateRate = 60;  // seconds between readings

void setup() {
    Logger.begin(candidates, sizeof(candidates) / sizeof(candidates[0]));
}

void loop() {
    Logger.run(updateRate);
}
