// A Margay that names no sensor at all: compile test (NW-Tests).
// NW_AllSensors.h is generated by `nw sensors` (NW-Build) from the libraries the
// workspace holds, and carries one instance of each with the table over them.
// The logger comes up, asks the bus, and holds whatever answered to a name it
// recognises (LIBRARY-DESIGN.md section 16 part (c)).
//
// Regenerate the header rather than editing it: in NW-Build,
//   nw sensors -o <this directory>/NW_AllSensors.h
// This sketch measures what the whole table costs, which is the number section
// 16 quotes: every library in it is instantiated and therefore linked.
#include <Margay.h>
#include "NW_AllSensors.h"

Margay Logger(MODEL_3v0);  // update to match your hardware version

uint32_t updateRate = 60;  // seconds between readings

void setup() {
    Logger.begin(nwAllSensors, nwAllSensorsCount);
}

void loop() {
    Logger.run(updateRate);
}
