// NW_AllSensors.h: every sensor this workspace can watch, and the table
// NW_Logger::discover() reads it from.
//
// Generated by `nw sensors` (NW-Build). Do not edit: run the command again.
// A sketch that includes this names no sensor of its own -
//
//     #include "NW_AllSensors.h"
//     Margay Logger(MODEL_3v0);
//     void setup() { Logger.begin(nwAllSensors, nwAllSensorsCount); }
//     void loop()  { Logger.run(900); }
//
// and the bus decides what is logged. Every sensor here is instantiated,
// which links every library here: a whole-workspace table costs more flash
// than a sketch naming the two sensors it has. One object holds one address
// at a time, so two boards of the same kind need a second entry - add it by
// hand in the sketch, beside this table, rather than here.

#ifndef NW_ALL_SENSORS_H
#define NW_ALL_SENSORS_H

#include <NW_Core.h>
#include <Apis.h>
#include <Walrus_I2C.h>
#include <Haar.h>
#include <Libelle.h>

static Apis nwApis;        // Apis_Library
static Walrus nwWalrus;    // Walrus_Library
static Haar nwHaar;        // Haar_Library
static Libelle nwLibelle;  // Libelle_Library

static NW_Sensor* nwAllSensors[] = {&nwApis, &nwWalrus, &nwHaar, &nwLibelle};
static const uint8_t nwAllSensorsCount = 4;

#endif
