// Two sensors on a Margay, programmed: the sketch names them and the logger
// holds them (NW-Tests). Hand-written rather than generated by make_sketches.py,
// because it pairs with Discovered_Margay: on the same bus the two write the
// same table, byte for byte (LIBRARY-DESIGN.md section 16).
//
// The sensors are watched in ADDRESS order, which is the order discovery finds
// them in, so the comparison is a plain diff with nothing to normalise. A
// deployment is free to watch in any order it likes - column order is
// unimportant - and this constraint is on the test, not on the library.
#include <Margay.h>
#include <Apis.h>
#include <Walrus_I2C.h>

Margay Logger(MODEL_3v0);  // update to match your hardware version
Apis distance;             // 0x41
Walrus stage;              // 0x57

uint32_t updateRate = 60;  // seconds between readings

void setup() {
    Logger.watch(distance);
    Logger.watch(stage);
    Logger.begin();
}

void loop() {
    Logger.run(updateRate);
}
